name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: [Linux]
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y  # Install Rust
          cargo install mdbook
          mdbook build -d build
          echo "Built the Ripple User Manual."

      - name: Deploy
        env:
          HOME: ${{ runner.temp }}
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: BuildHexagon
        run: |
          cd opt/hexagon && mdbook build -d build
          echo "Built the Hexagon optimizaton guide."

      - name: DeployHexagon
        env:
          HOME: ${{ runner.temp }}
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./opt/hexagon/build
          destination_dir: 'opt/hexagon'
